---
abstract: 'Test applications using Selenium Remote Control'
author:
  - 'Luke Closs <test-www-selenium@awesnob.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::Mock::LWP: 0
  Test::More: 0.42
  Test::Pod: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WWW-Selenium
no_index:
  directory:
    - inc
    - t
requires:
  LWP::UserAgent: 0
  URI::Escape: 1.31
resources:
  license: http://dev.perl.org/licenses/
version: 1.21
