--- #YAML:1.0
name: Test-WWW-Selenium
version: 0.02
author:
  - Mattia Barbon <mbarbon@cpan.org>
abstract: Tesing applications using WWW::Selenium
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
